<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修.NET CAD二次开发学习 直线画矩形并转换成组' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>.NET CAD二次开发学习 直线画矩形并转换成组</center></div><div class='banquan'>原文出处:本文由博客园博主yannis.wh,yang提供。<br/>
原文连接:https://www.cnblogs.com/yannisCad/p/10677558.html</div><br>
    <p><strong><span style="color: #ff6600; font-size: 15px;">主要代码：</span></strong></p>
<p><strong><span style="color: #ff6600; font-size: 15px;">using System;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using System.Collections.Generic;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using System.Linq;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using System.Text;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using System.Threading.Tasks;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using GrxCAD.Runtime;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using GrxCAD.ApplicationServices;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using GrxCAD.EditorInput;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using GrxCAD.Geometry;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using GrxCAD.DatabaseServices;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">using GrxCAD.Windows;</span></strong></p>
<p><strong><span style="color: #ff6600; font-size: 15px;">namespace ArxFirstTest</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">{</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">    public class XRect</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">    {</span></strong><br />        <br /><strong><span style="color: #ff6600; font-size: 15px;">        private Point3d StartPoint;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">        private Point3d EndPoint;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">        private double width;</span></strong><br />     <br /><strong><span style="color: #ff6600; font-size: 15px;">        public void XrecPic()</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">        {</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            Document doc = Application.DocumentManager.MdiActiveDocument;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            Editor editor = doc.Editor;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            Database db = doc.Database;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            PromptPointOptions promptPoint1 = new PromptPointOptions("\n请指定起点&lt;退出&gt;");</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            PromptPointResult pointResult1 = editor.GetPoint(promptPoint1);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            PromptPointOptions promptPoint2 = new PromptPointOptions("\n请指定终点&lt;退出&gt;");</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            PromptPointResult pointResult2 = editor.GetPoint(promptPoint2);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            PromptDoubleOptions pDoubleOptions = new PromptDoubleOptions("\n请输入宽度&lt;退出&gt;");</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            PromptDoubleResult pDoubleRes = editor.GetDouble(pDoubleOptions);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            if (pointResult1.Status == PromptStatus.OK &amp;&amp; pointResult2.Status == PromptStatus.OK &amp;&amp; pDoubleRes.Value &gt; 0)</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            {</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                using (Transaction trans = doc.TransactionManager.StartTransaction())</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                {</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    StartPoint = pointResult1.Value;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    EndPoint = pointResult2.Value;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    width = pDoubleRes.Value;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Line line = new Line();</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    line.StartPoint = StartPoint;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    line.EndPoint = EndPoint;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    DBObjectCollection dboj = line.GetOffsetCurves(width / 2);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    DBObjectCollection dboj1 = line.GetOffsetCurves(width / 2 - width);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Line line1 = (Line)dboj[0];</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Line line2 = (Line)dboj1[0];</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Line line3 = new Line();</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Line line4 = new Line();</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    line3.StartPoint = line1.StartPoint;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    line3.EndPoint = line2.StartPoint;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    line4.StartPoint = line1.EndPoint;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    line4.EndPoint = line2.EndPoint;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    ObjectId idModelSpace = SymbolUtilityServices.GetBlockModelSpaceId(db);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    BlockTableRecord btr = trans.GetObject(idModelSpace, OpenMode.ForWrite) as BlockTableRecord;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    btr.AppendEntity(line1);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    btr.AppendEntity(line2);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    btr.AppendEntity(line3);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    btr.AppendEntity(line4);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    trans.AddNewlyCreatedDBObject(line1, true);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    trans.AddNewlyCreatedDBObject(line2, true);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    trans.AddNewlyCreatedDBObject(line3, true);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    trans.AddNewlyCreatedDBObject(line4, true);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Entity ent1 = (Entity)line1;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Entity ent2 = (Entity)line2;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Entity ent3 = (Entity)line3;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Entity ent4 = (Entity)line4;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    Group group = new Group();</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    group.Append(ent1.ObjectId);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    group.Append(ent2.ObjectId);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    group.Append(ent3.ObjectId);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    group.Append(ent4.ObjectId);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    DBDictionary groupdic = trans.GetObject(db.GroupDictionaryId,OpenMode.ForWrite) as DBDictionary;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    group.Selectable = true;</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    groupdic.SetAt(group.Name, group);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    trans.AddNewlyCreatedDBObject(group, true);</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                    trans.Commit();</span></strong><br />                    <br /><strong><span style="color: #ff6600; font-size: 15px;">                }</span></strong></p>
<p><strong><span style="color: #ff6600; font-size: 15px;">            }</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            else</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">            {</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                Application.ShowAlertDialog("选择或者输入有误,请重新输入");</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">                return;</span></strong></p>
<p><strong><span style="color: #ff6600; font-size: 15px;">            }</span></strong></p>
<p><strong><span style="color: #ff6600; font-size: 15px;">        }</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">    }</span></strong><br /><strong><span style="color: #ff6600; font-size: 15px;">}</span></strong></p>
<p><strong><span style="color: #ff6600; font-size: 15px;">&nbsp;</span></strong></p>
</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>